package org.t_robop.ikalendar;

import io.realm.Realm;
import io.realm.RealmObject;
import io.realm.annotations.Ignore;


/**
 * Created by Kai on 2017/07/03.
 */

public class DataBase extends RealmObject {

    private String          name;
    private int             id;

    @Ignore
    private int             sessionId;

    // Standard getters & setters generated by your IDE…
    public String getName() { return name; }
    public void   setName(String name) { this.name = name; }
    public int    getId() { return id; }
    public void   setId(int id) { this.id = id; }
    public int    getSessionId() { return sessionId; }
    public void   setSessionId(int sessionId) { this.sessionId = sessionId; }
}
